server:
  port: 0

spring:
  application:
    name: manager-service

mybatis:
  type-aliases-package: com.example.mappertut.model
  mapper-locations: mybatis-mapper/*.xml
  configuration.map-underscore-to-camel-case: true


