server:
  port: 2200

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://203.250.32.29:5001/engbase
    username: rooteng
    password: eng1234
  servlet:
    multipart:
      file-size-threshold: 1MB
#      location: /home/icslab/ENG-store/image/content/
      location: /Users/jeonghunlee/image/content/
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.example.mappertut.model
  mapper-locations: mybatis-mapper/*.xml
  configuration.map-underscore-to-camel-case: true
