server:
  port: 10000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://203.250.32.29:5001/engbase
    username: rooteng
    password: eng1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 203.250.32.29
    port: 5002
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
#  redis:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        port: 6379
#        host: 203.250.32.29


  mail:
    host: smtp.gmail.com
    port: 587
    username: agc01075547865@gmail.com
    password: cavnafppgwedyiur
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  type-aliases-package: com.example.mappertut.model
  mapper-locations: mybatis-mapper/*.xml
  configuration.map-underscore-to-camel-case: true
