spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: ukidd12
    password: ljh90140189!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: jlchj.iptime.org
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: /home/icslab/ENG-store/image/content/
      # location: /Users/jeonghunlee/image/content/
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://jlchj.iptime.org:8761/eureka

secret_settings:
  address: ukidd12@naver.com