spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jlchj.iptime.org:5001/eng?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: eng1234
  servlet:
    multipart:
      max-file-size: 51200KB
      max-request-size: 51200KB

  redis:
    host: jlchj.iptime.org
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

  mail:
    host: smtp.gmail.com
    port: 587
    username: agc01075547865@gmail.com
    password: axaviysasbikuhtg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  type-aliases-package: com.example.mappertut.model
  mapper-locations: mybatis-mapper/*.xml
  configuration.map-underscore-to-camel-case: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://jlchj.iptime.org:8761/eureka
