server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://home/eng2/ENG-SERVER/config-files

path:
  text: ${user.home}